# model 
model_id: RAFS

# multi-GPUs
use_mGPU: True

# validation
use_validation: True

# wandb
use_wandb: True
wandb_alert_thres: 1000

# root
train_dataset_root_list: [
                '/home/compu/dataset/CelebHQ',
                '/home/compu/dataset/ffhq16k'
            ]
valid_dataset_root: assets/valid
save_root: train_result

# learning rate
lr_G: 0.0001
lr_D: 0.00001
beta1: 0.9
beta2: 0.999

# weight of loss
W_id: 0.15
W_recon: 1
W_lpips: 0.8
W_token: 1

# hyperparameters
same_prob: 0.2
batch_per_gpu: 8
max_step: 400000

# log cycle
loss_cycle: 10
test_cycle: 100
ckpt_cycle: 4000

# ckpt path
# blank is None, but None is "None"
load_ckpt: True
ckpt_id: third_try_Transformer
ckpt_step: 